[project]
name = "skryzhal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bzadorozhnyi", email = "bohzador@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "loguru>=0.7.3",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.52",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.2",
    "ty>=0.0.71",
    "typer>=0.27.1",
]

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
preview = true
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "C901", "PLR1702"]
ignore = ["E731"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-nested-blocks = 4

[tool.ruff.format]
quote-style = "double"
