"""add lease to render jobs

Revision ID: b8cedbd38c3c
Revises: 58dfed4c1f73
Create Date: 2026-08-19 13:41:17.343950

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8cedbd38c3c"
down_revision: str | Sequence[str] | None = "58dfed4c1f73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "render_jobs", sa.Column("locked_until", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("render_jobs", "locked_until")
    # ### end Alembic commands ###
